# Generated by Django 4.2.2 on 2023-06-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_thread_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat_room',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
