# Generated by Django 4.1.5 on 2023-06-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_group_groupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_admin',
            field=models.ManyToManyField(related_name='group_admins', to='chat.myuser'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
