# Generated by Django 4.1.5 on 2023-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_group_group_admin_groupchat_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
