# Generated by Django 4.2.2 on 2023-06-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_group_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
